Enable commitmentHash preclaim in tests
aeternity/aepp-sdk-js pull request #1262
Opened 2021-07-28 11:43 UTC by mradkov

2021-07-30 07:50 UTC, marc0olo requested changes

2021-07-30 07:50 UTC, marc0olo commented on test/integration/contract.js
>        const { salt: _salt } = await contract.aensPreclaim(name)
the `aensPreclaim` should be replace with the contract call and delegation signature.

2021-07-30 07:50 UTC, marc0olo commented on test/integration/contract.js
> +      const commitmentId = commitmentHash(name, _salt)
the salt used here needs to be generated with the utils independent from the `aensPreclaim` method

2021-10-15 16:22 UTC, davidyuk approved these changes

2021-10-17 19:29 UTC, marc0olo commented
@mradkov I made some mistake. fixed it and squashed to commits into one. it's unfortunate to not see tests failing due to that linting and codecov errors

2021-10-20 08:48 UTC, mradkov reviewed
LGTM now

2021-10-20 08:48 UTC, merged