fix(wallet): make extension connection on demand
aeternity/aepp-sdk-js pull request #1578
Opened 2022-06-22 05:05 UTC by subhod-i

The `browser.runtime.connect()` code in `content-script.js` file opens a connection with the extension wallet on every page resulting in `n` number of RPC clients where n= number of tabs open. Foreach connection wallet keeps on sending its info on `setInterval`.

Solution: Create a runtime connection only when there is a special request from the webpage. The difference between a standard web page and an aepp page is wallet detector. Added a special request `scan`. Overall the connection is established in the `connection-proxy` file only when a webpage sends `scan` request using wallet detector. Existing interfaces work as it is.

2022-06-22 05:08 UTC, subhod-i commented on src/AeSdkWallet.ts
> +          [METHODS.scan]: async () => this.shareWalletInfo(id),
Sharing wallet info on demand. This eliminates `setInterval` loop.

2022-06-22 05:08 UTC, subhod-i commented on src/aepp-wallet-communication/connection-proxy.ts
> +    if (!con2.isConnected() && msg.method === METHODS.scan) {
Establish browserRuntime connection only when a page establishes a connection.

2022-06-22 05:10 UTC, subhod-i commented on src/aepp-wallet-communication/connection/BrowserRuntime.ts
> +    this.port = this.port ?? this.setPort();
made `port` optional. connect on demand.

2022-06-29 20:43 UTC, davidyuk requested changes
The original goal wasn't formulated properly, we can have extra connection, but they shouldn't appear in the set of rpc clients before aepp is connected. Alternatively, it can be solved by distinglishing connected clients with not connected (I've missed this option before).

More clear way to do don't store extra rpc clients in `wallet._clients` is to extract connection logic from `addRpcClient` and `shareWalletInfo`. And only after aepp called `METHODS.connect` to call `addRpcClient`.

But this refactoring doesn't seems to be required because I found a workaround using `_isRpcClientConnected`

2022-07-01 10:10 UTC, closed without merging